# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  hds-benchmarks:
    dependencies:
    - base
    - hds
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: My attempt to learn Haskell
executables:
  hds:
    dependencies:
    - base
    - hds
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/hds
library:
  dependencies:
  - base
  source-dirs: library
license: MIT
maintainer: Author name here
name: hds
synopsis: My attempt to understand Haskell
tests:
  hds-test-suite:
    dependencies:
    - base
    - hds
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
